require_relative "gtk3_ffi/bindings/glib"
require_relative "gtk3_ffi/bindings/gobject"
require_relative "gtk3_ffi/bindings/gtk"
require_relative "gtk3_ffi/bindings/cairo"
require_relative "gtk3_ffi/controller"
